name: radx-destiller

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - pandas
  - pyarrow
  - openpyxl
  - levenshtein
  - titlecase
  - nameparser
  - inflection
  - fake-useragent
  - tqdm
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - umap-learn
  - pydantic
  - black
  - pylint
  - vulture
  - python-dotenv=1.0.0
  - openssl
  - openai
  - langchain
  - langchain-community
  - tiktoken
  - pypdf
  - lxml
  - tenacity
  - requests
  - beautifulsoup4


